# -*- coding: utf-8 -*-
"""info_assign3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1FxC-K7f7obL3zLLRjPJWtlEAIuy498
"""

!apt-get install -y -qq nmap
!pip install streamlit plotly -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

import streamlit, plotly, subprocess
nmap_v = subprocess.run(['nmap','--version'], capture_output=True, text=True)

import os
os.environ['VT_API_KEY']     = 'API_KEY'
os.environ['GMAIL_SENDER']   = 'nikhithamondeddu@gmail.com'
os.environ['GMAIL_PASSWORD'] = 'kyttdnznjmkqqqdp'
os.environ['GMAIL_RECIPIENT']= 'nikhithamondeddu@gmail.com'
os.environ['SCAN_TARGETS']   = 'testasp.vulnweb.com,testphp.vulnweb.com'

import os
try:
    from google.colab import userdata
    VT_API_KEY      = userdata.get('VT_API_KEY')      or os.environ.get('VT_API_KEY', '')
    sender_email    = userdata.get('GMAIL_SENDER')    or os.environ.get('GMAIL_SENDER', '')
    app_password    = userdata.get('GMAIL_PASSWORD')  or os.environ.get('GMAIL_PASSWORD', '')
    recipient_email = userdata.get('GMAIL_RECIPIENT') or os.environ.get('GMAIL_RECIPIENT', '')
    targets_env     = userdata.get('SCAN_TARGETS')    or os.environ.get('SCAN_TARGETS', '')
    print('Running in Colab — reading from Colab Secrets ✅')
except Exception:
    VT_API_KEY      = os.environ.get('VT_API_KEY', '')
    sender_email    = os.environ.get('GMAIL_SENDER', '')
    app_password    = os.environ.get('GMAIL_PASSWORD', '')
    recipient_email = os.environ.get('GMAIL_RECIPIENT', '')
    targets_env     = os.environ.get('SCAN_TARGETS', '')
    print('Running outside Colab — reading from os.environ')

print()
for name, val in [('VT_API_KEY', VT_API_KEY), ('sender_email', sender_email),
                  ('app_password', app_password), ('recipient_email', recipient_email),
                  ('targets_env', targets_env)]:
    print(f'  {name:<22} : {"set" if val else "empty"}')

import requests

def scan_vulnerabilities(target):

    results = []

    try:
        url = f"http://{target}"

        response = requests.get(url, timeout=5)
        headers = response.headers

        # 1. Missing Security Headers
        if "X-Frame-Options" not in headers:
            results.append(("Missing X-Frame-Options", "Medium", 5))

        if "Content-Security-Policy" not in headers:
            results.append(("Missing CSP Header", "High", 8))

        # 2. Server Disclosure
        if "Server" in headers:
            results.append(("Server Version Disclosure", "Low", 3))

        # 3. HTTP instead of HTTPS
        if url.startswith("http://"):
            results.append(("Not using HTTPS", "High", 9))

        # 4. Open Admin Panel
        admin_paths = ["/admin", "/login", "/dashboard"]

        for path in admin_paths:
            try:
                r = requests.get(url + path, timeout=3)
                if r.status_code == 200:
                    results.append(("Open Admin Panel", "Critical", 12))
            except:
                pass

        # 5. SQL Injection Test (basic)
        try:
            sqli = requests.get(url + "?id=1' OR '1'='1", timeout=3)
            if "sql" in sqli.text.lower():
                results.append(("Possible SQL Injection", "Critical", 13))
        except:
            pass

    except:
        results.append(("Target Unreachable", "Informational", 1))

    return results

class State:
    df= 'previous scan results'
    scan_time= '2026-03-12 09:00:00'
    last_refreshed = '12 Mar 2026  09:00:00'

s = State()
print('BEFORE refresh:')
print(f'df= "{s.df}"')
print(f'last_refreshed = "{s.last_refreshed}"')
print()

s.df = s.scan_time = s.last_refreshed = None

print('AFTER refresh clicked:')
print(f'df= {s.df}   ← cleared, new scan will run')
print(f'last_refreshed = {s.last_refreshed}   ← cleared')
print()
print('Dashboard now shows "No scan run yet" while new scan is in progress.')

print('SIDEBAR REFRESH: dashboard.py code:')
print('''
scan_button= st.sidebar.button("🚀 Run Full Scan", type="primary")
refresh_button = st.sidebar.button("🔄 Refresh Scan")

if scan_button or refresh_button:
    if refresh_button:
        st.session_state.df= None
        st.session_state.scan_time= None
        st.session_state.last_refreshed = None
    #scan runs below as normal
''')

print('TOP-OF-DASHBOARD REFRESH — dashboard.py code:')
print('''
col_ref, col_btn = st.columns([6, 1])   # 6:1 width — timestamp gets most space
with col_btn:
    if st.button("🔄 Refresh", use_container_width=True):
        st.session_state.df= None
        st.session_state.last_refreshed = None
        st.rerun() # immediately restart the script
''')

from datetime import datetime

print('st.rerun() EXECUTION ORDER')
print('=' * 45)
print('''
Normal Streamlit rerun:
  1. User clicks widget
  2. Current code finishes executing completely
  3. THEN script restarts from the top

With st.rerun():
  1. Code reaches st.rerun()
  2. Script IMMEDIATELY restarts from line 1
  3. Everything after st.rerun() is NOT executed

Why we need it for Refresh:
  Without st.rerun() → user clicks Refresh, session_state clears,
  but the page looks the same until they next interact with something.

  With st.rerun()    → user clicks Refresh, page instantly shows
  the cleared state. Much better user experience.
''')

import streamlit as st
from datetime import datetime
st.session_state.last_refreshed = datetime.now().strftime('%d %b %Y  %H:%M:%S')

#displaying at the top of dashboard only giving warning becoz this is not running on streamlit
col_ref, col_btn = st.columns([6, 1])    # col_ref is 6x wider than col_btn

with col_ref:
    if st.session_state.get('last_refreshed'):
        st.info(f"🕐 Last refreshed: {st.session_state.last_refreshed}")
    else:
        st.info("🕐 No scan run yet — click Run Full Scan in the sidebar.")

with col_btn:
    if st.button('🔄 Refresh', use_container_width=True):
        st.session_state.df = None
        st.session_state.last_refreshed = None
        st.rerun()

import time
from datetime import datetime

session = {'last_refreshed': None, 'df': None}

def show_banner():
    if session['last_refreshed']:
        print(f'  🔵  🕐 Last refreshed: {session["last_refreshed"]}')
    else:
        print(f'  🔵  🕐 No scan run yet — click Run Full Scan in the sidebar.')

print('State 1 — no scan yet:')
show_banner()
print()

session['last_refreshed'] = datetime.now().strftime('%d %b %Y  %H:%M:%S')
session['df'] = 'scan results'
print('State 2 — scan complete:')
show_banner()
print()

session['df'] = session['last_refreshed'] = None
print('State 3 — refresh clicked (cleared):')
show_banner()

import streamlit as st
import subprocess
import xml.etree.ElementTree as ET
import requests
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import time
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# -------------------------------
# PAGE CONFIG
# -------------------------------
st.set_page_config(
    page_title="CyberScan",
    page_icon="🛡️",
    layout="wide"
)

# -------------------------------
# HEADER
# -------------------------------
st.title("🛡️ CyberScan")
st.caption(" Vulnerability Scanner & Risk Intelligence Dashboard")

# -------------------------------
# LEFT SIDEBAR NAVIGATION
# -------------------------------
st.sidebar.title("🛡️ CyberScan")

menu = st.sidebar.radio(
    "Navigation",
    [
        "CyberScan",
        "Scan Data",
        "Charts",
        "Threat Intel",
        "Alerts"
    ]
)

st.sidebar.divider()

# -------------------------------
# LOAD SECRETS
# -------------------------------
try:
    from google.colab import userdata
    VT_API_KEY      = userdata.get("VT_API_KEY") or os.environ.get("VT_API_KEY", "")
    sender_email    = userdata.get("GMAIL_SENDER") or os.environ.get("GMAIL_SENDER", "")
    app_password    = userdata.get("GMAIL_PASSWORD") or os.environ.get("GMAIL_PASSWORD", "")
    recipient_email = userdata.get("GMAIL_RECIPIENT") or os.environ.get("GMAIL_RECIPIENT", "")
    targets_env     = userdata.get("SCAN_TARGETS") or os.environ.get("SCAN_TARGETS", "")
except:
    VT_API_KEY      = os.environ.get("VT_API_KEY", "")
    sender_email    = os.environ.get("GMAIL_SENDER", "")
    app_password    = os.environ.get("GMAIL_PASSWORD", "")
    recipient_email = os.environ.get("GMAIL_RECIPIENT", "")
    targets_env     = os.environ.get("SCAN_TARGETS", "")

DEFAULT_TARGETS = "testasp.vulnweb.com,testphp.vulnweb.com"
targets = [t.strip() for t in (targets_env or DEFAULT_TARGETS).split(",") if t.strip()]

# -------------------------------
# STATUS PANEL
# -------------------------------
st.sidebar.subheader("⚙️ Status")

if VT_API_KEY:
    st.sidebar.success("VirusTotal API Ready")
else:
    st.sidebar.error("VT_API_KEY Missing")

if sender_email and app_password and recipient_email:
    st.sidebar.success("Email Alerts Ready")
else:
    st.sidebar.warning("Email Alerts Not Configured")

st.sidebar.caption(f"Targets: {', '.join(targets)}")

st.sidebar.divider()

# -------------------------------
# SCAN BUTTONS
# -------------------------------
scan_button = st.sidebar.button("🚀 Run Scan")
refresh_button = st.sidebar.button("🔄 Refresh")

# -------------------------------
# SCAN DIRECTORY
# -------------------------------
SCAN_DIR = "scan_results"
os.makedirs(SCAN_DIR, exist_ok=True)

HIGH_RISK_SERVICES = {
    "ftp":4,
    "telnet":5,
    "ssh":2,
    "smtp":3,
    "rdp":5,
    "vnc":4,
    "http":2,
    "https":1,
    "mysql":4,
    "postgresql":4,
    "mongodb":5,
    "redis":5,
    "dns":2
}

# -------------------------------
# FUNCTIONS
# -------------------------------
def run_nmap_scan(target):
    xml_file = f"{SCAN_DIR}/{target}.xml"
    subprocess.run(["nmap","-Pn","-sV","-oX",xml_file,target],capture_output=True)
    return xml_file

def parse_nmap_xml(xml_file):

    root = ET.parse(xml_file).getroot()

    rows = []

    for host in root.findall("host"):
        ip = host.find("address").get("addr")

        for port in host.findall(".//port"):

            svc = port.find("service")

            rows.append({
                "ip":ip,
                "port":port.get("portid"),
                "service":svc.get("name") if svc is not None else "unknown"
            })

    return rows


def check_virustotal(ip,api):

    try:
        r = requests.get(
            f"https://www.virustotal.com/api/v3/ip_addresses/{ip}",
            headers={"x-apikey":api},
            timeout=10
        )

        return r.json()["data"]["attributes"]["last_analysis_stats"]["malicious"]

    except:
        return 0


def calculate_risk(row):

    base = HIGH_RISK_SERVICES.get(row["service"],1)

    vt = row["malicious_reports"]

    port_factor = int(row["port"]) % 5

    risk_score = base + vt + port_factor

    return risk_score


def classify_severity(score):

    if score >= 12:
        return "Critical"

    elif score >= 8:
        return "High"

    elif score >= 5:
        return "Medium"

    elif score >= 3:
        return "Low"

    else:
        return "Informational"


# Define severity colors globally
severity_colors = {
    "Critical":"#ff0000",
    "High":"#ff6b6b",
    "Medium":"#ffa94d",
    "Low":"#4dabf7",
    "Informational":"#51cf66"
}

# -------------------------------
# SESSION STATE
# -------------------------------
if "df" not in st.session_state:
    st.session_state.df = None

# -------------------------------
# RUN SCAN
# -------------------------------
if scan_button:

    all_rows=[]

    for target in targets:

        rows = parse_nmap_xml(run_nmap_scan(target))

        all_rows.extend(rows)

    df = pd.DataFrame(all_rows)

    vt={}

    for ip in df["ip"].unique():

        vt[ip]=check_virustotal(ip,VT_API_KEY)

        time.sleep(15)

    df["malicious_reports"]=df["ip"].map(vt)

    df["risk_score"]=df.apply(calculate_risk,axis=1)

    df["severity"]=df["risk_score"].apply(classify_severity)

    st.session_state.df=df

# -------------------------------
# SAMPLE DATA IF NONE
# -------------------------------
if "df" not in st.session_state:
    st.session_state.df = None

# -------------------------------
# LOAD DATA SAFELY
# -------------------------------
if st.session_state.df is None:

    df = pd.DataFrame({
        "ip": [
            "192.168.1.1","192.168.1.1","192.168.1.2",
            "192.168.1.2","192.168.1.3","192.168.1.3"
        ],
        "port": ["22","80","21","443","23","8080"],
        "service": ["ssh","http","ftp","https","telnet","http"],
        "malicious_reports": [0,1,2,3,5,4]
    })

    df["risk_score"] = df.apply(calculate_risk, axis=1)
    df["severity"] = df["risk_score"].apply(classify_severity)

else:
    df = st.session_state.df


# -------------------------------
# PAGE: CYBERSCAN
# -------------------------------
if menu=="CyberScan":

    st.subheader("Dashboard Overview")

    c1,c2,c3,c4=st.columns(4)

    c1.metric("Hosts",df["ip"].nunique())
    c2.metric("Open Ports",len(df))
    c3.metric("Services",df["service"].nunique())
    c4.metric("Max Risk",df["risk_score"].max())


# -------------------------------
# PAGE: SCAN DATA
# -------------------------------
elif menu=="Scan Data":

    st.subheader("Scan Results")

    st.dataframe(df,use_container_width=True)


# -------------------------------
# PAGE: CHARTS
# -------------------------------
elif menu=="Charts":

    st.subheader("Security Charts")

    chart_df = df.groupby(["ip", "severity"]).size().reset_index(name="count")

    fig = px.bar(
        chart_df,
        x="ip",
        y="count",
        color="severity",
        title="Risk Distribution by Host"
    )

    st.plotly_chart(fig,use_container_width=True)


# -------------------------------
# PAGE: THREAT INTEL
# -------------------------------
elif menu=="Charts":

    st.subheader("📊 Security Charts")

    # 1️⃣ Severity Pie
    sev_df = df["severity"].value_counts().reset_index()
    sev_df.columns = ["severity", "count"]

    fig1 = px.pie(sev_df, names="severity", values="count")
    st.plotly_chart(fig1, use_container_width=True)

    # 2️⃣ Risk per Host
    risk_df = df.groupby("ip")["risk_score"].sum().reset_index()

    fig2 = px.bar(risk_df, x="ip", y="risk_score")
    st.plotly_chart(fig2, use_container_width=True)

    # 3️⃣ Services
    svc_df = df["service"].value_counts().reset_index()
    svc_df.columns = ["service", "count"]

    fig3 = px.bar(svc_df, x="service", y="count")
    st.plotly_chart(fig3, use_container_width=True)

    # 4️⃣ Severity by Host (THIS FIXES YOUR ERROR)
    chart_df = df.groupby(["ip","severity"]).size().reset_index(name="count")

    fig4 = px.bar(
        chart_df,
        x="ip",
        y="count",
        color="severity"
    )

    st.plotly_chart(fig4, use_container_width=True)

    # -------------------------------
    # 2️⃣ Risk per Host (Bar)
    # -------------------------------
    risk_df = df.groupby("ip")["risk_score"].sum().reset_index()

    fig2 = px.bar(
        risk_df,
        x="ip",
        y="risk_score",
        title="Total Risk per Host"
    )

    st.plotly_chart(fig2, use_container_width=True)

    st.divider()

    # -------------------------------
    # 3️⃣ Services Distribution
    # -------------------------------
    svc_df = df["service"].value_counts().reset_index()
    svc_df.columns = ["service", "count"]

    fig3 = px.bar(
        svc_df,
        x="service",
        y="count",
        title="Services Exposed"
    )

    st.plotly_chart(fig3, use_container_width=True)

    st.divider()

    # -------------------------------
    # 4️⃣ Severity by Host (Advanced)
    # -------------------------------
    chart_df = df.groupby(["ip", "severity"]).size().reset_index(name="count")

    fig4 = px.bar(
        chart_df,
        x="ip",
        y="count",
        color="severity",
        title="Risk Distribution by Host"
    )

    st.plotly_chart(fig4, use_container_width=True)


# -------------------------------
# PAGE: ALERTS
# -------------------------------
def send_alert_email(sender_email, password, recipient_email, df, target):

    high_df = df[df["severity"].isin(["High", "Critical"])]

    # ❌ Do NOT send if no high/critical
    if high_df.empty:
        return "No alert triggered"

    scan_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    overall_risk = int(df["risk_score"].sum())

    # -------------------------------
    # BUILD HTML EMAIL
    # -------------------------------
    html = f"""
    <h2 style="color:red;">🚨 CyberScan Security Alert</h2>

    <p><b>Target:</b> {target}</p>
    <p><b>Scan Time:</b> {scan_time}</p>
    <p><b>Overall Risk Score:</b> {overall_risk}</p>

    <h3>High & Critical Vulnerabilities</h3>

    <table border="1" cellpadding="6" cellspacing="0">
        <tr style="background-color:#f2f2f2;">
            <th>Vulnerability</th>
            <th>Severity</th>
            <th>Risk Score</th>
        </tr>
    """

    # -------------------------------
    # TABLE DATA
    # -------------------------------
    for _, row in high_df.iterrows():
        html += f"""
        <tr>
            <td>{row['service']}</td>
            <td>{row['severity']}</td>
            <td>{row['risk_score']}</td>
        </tr>
        """

    html += "</table><br>"

    # -------------------------------
    # RECOMMENDATIONS
    # -------------------------------
    html += "<h3>Recommended Actions</h3><ul>"

    for _, row in high_df.iterrows():

        if "SQL" in row["service"]:
            rec = "Sanitize inputs and use prepared statements"
        elif "Admin" in row["service"]:
            rec = "Restrict admin panel access"
        elif "HTTPS" in row["service"]:
            rec = "Enable HTTPS encryption"
        else:
            rec = "Review and secure this service"

        html += f"<li><b>{row['service']}:</b> {rec}</li>"

    html += "</ul>"

    # -------------------------------
    # DISCLAIMER
    # -------------------------------
    html += """
    <hr>
    <p style="color:gray; font-size:12px;">
    This is an automated alert generated by CyberScan.
    Please verify findings before taking action.
    </p>
    """

    # -------------------------------
    # EMAIL SETUP
    # -------------------------------
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚨 {target} - HIGH/CRITICAL Vulnerabilities Detected"
    msg["From"] = sender_email
    msg["To"] = recipient_email

    msg.attach(MIMEText(html, "html"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, password)
        server.send_message(msg)
        server.quit()
        return "Email Sent Successfully"

    except Exception as e:
        return str(e)

# Assuming 'targets' list is available from previous cells
# For demonstration, pick the first target from the 'targets' list.
# In a real Streamlit app, 'target' would come from the scan loop or user selection.
target_for_alert = targets[0] if targets else "unknown_target"

send_alert_email(
    sender_email,
    app_password,
    recipient_email,
    df,
    target_for_alert
)

import os

# Save the dashboard code to a file
dashboard_code = '''
import streamlit as st
import subprocess
import xml.etree.ElementTree as ET
import requests
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import time
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# -------------------------------
# PAGE CONFIG
# -------------------------------
st.set_page_config(
    page_title="CyberScan",
    page_icon="🛡️",
    layout="wide"
)

# -------------------------------
# HEADER
# -------------------------------
st.title("🛡️ CyberScan")
st.caption("Vulnerability Scanner & Risk Intelligence Dashboard")

# -------------------------------
# LEFT SIDEBAR NAVIGATION
# -------------------------------
st.sidebar.title("🛡️ CyberScan")

menu = st.sidebar.radio(
    "Navigation",
    [
        "CyberScan",
        "Scan Data",
        "Charts",
        "Threat Intel",
        "Alerts"
    ]
)

st.sidebar.divider()

# -------------------------------
# LOAD SECRETS
# -------------------------------
try:
    from google.colab import userdata
    VT_API_KEY      = userdata.get("VT_API_KEY") or os.environ.get("VT_API_KEY", "")
    sender_email    = userdata.get("GMAIL_SENDER") or os.environ.get("GMAIL_SENDER", "")
    app_password    = userdata.get("GMAIL_PASSWORD") or os.environ.get("GMAIL_PASSWORD", "")
    recipient_email = userdata.get("GMAIL_RECIPIENT") or os.environ.get("GMAIL_RECIPIENT", "")
    targets_env     = userdata.get("SCAN_TARGETS") or os.environ.get("SCAN_TARGETS", "")
except:
    VT_API_KEY      = os.environ.get("VT_API_KEY", "")
    sender_email    = os.environ.get("GMAIL_SENDER", "")
    app_password    = os.environ.get("GMAIL_PASSWORD", "")
    recipient_email = os.environ.get("GMAIL_RECIPIENT", "")
    targets_env     = os.environ.get("SCAN_TARGETS", "")

DEFAULT_TARGETS = "testasp.vulnweb.com,testphp.vulnweb.com"
targets = [t.strip() for t in (targets_env or DEFAULT_TARGETS).split(",") if t.strip()]

# -------------------------------
# STATUS PANEL
# -------------------------------
st.sidebar.subheader("⚙️ Status")

if VT_API_KEY:
    st.sidebar.success("VirusTotal API Ready")
else:
    st.sidebar.error("VT_API_KEY Missing")

if sender_email and app_password and recipient_email:
    st.sidebar.success("Email Alerts Ready")
else:
    st.sidebar.warning("Email Alerts Not Configured")

st.sidebar.caption(f"Targets: {', '.join(targets)}")

st.sidebar.divider()

# -------------------------------
# SCAN BUTTONS
# -------------------------------
scan_button = st.sidebar.button("🚀 Run Scan")
refresh_button = st.sidebar.button("🔄 Refresh")

# -------------------------------
# SCAN DIRECTORY
# -------------------------------
SCAN_DIR = "scan_results"
os.makedirs(SCAN_DIR, exist_ok=True)

HIGH_RISK_SERVICES = {
    "ftp":4,
    "telnet":5,
    "ssh":2,
    "smtp":3,
    "rdp":5,
    "vnc":4,
    "http":2,
    "https":1,
    "mysql":4,
    "postgresql":4,
    "mongodb":5,
    "redis":5,
    "dns":2
}

# -------------------------------
# FUNCTIONS
# -------------------------------
def run_nmap_scan(target):
    xml_file = f"{SCAN_DIR}/{target}.xml"
    subprocess.run(["nmap","-Pn","-sV","-oX",xml_file,target],capture_output=True)
    return xml_file

def parse_nmap_xml(xml_file):

    root = ET.parse(xml_file).getroot()

    rows = []

    for host in root.findall("host"):
        ip = host.find("address").get("addr")

        for port in host.findall(".//port"):

            svc = port.find("service")

            rows.append({
                "ip":ip,
                "port":port.get("portid"),
                "service":svc.get("name") if svc is not None else "unknown"
            })

    return rows


def check_virustotal(ip,api):

    try:
        r = requests.get(
            f"https://www.virustotal.com/api/v3/ip_addresses/{ip}",
            headers={"x-apikey":api},
            timeout=10
        )

        return r.json()["data"]["attributes"]["last_analysis_stats"]["malicious"]

    except:
        return 0


def calculate_risk(row):

    base = HIGH_RISK_SERVICES.get(row["service"],1)

    vt = row["malicious_reports"]

    port_factor = int(row["port"]) % 5

    risk_score = base + vt + port_factor

    return risk_score


def classify_severity(score):

    if score >= 12:
        return "Critical"

    elif score >= 8:
        return "High"

    elif score >= 5:
        return "Medium"

    elif score >= 3:
        return "Low"

    else:
        return "Informational"


# Define severity colors globally
severity_colors = {
    "Critical":"#ff0000",
    "High":"#ff6b6b",
    "Medium":"#ffa94d",
    "Low":"#4dabf7",
    "Informational":"#51cf66"
}

# -------------------------------
# SESSION STATE
# -------------------------------
if "df" not in st.session_state:
    st.session_state.df = None

# -------------------------------
# RUN SCAN
# -------------------------------
if scan_button:

    all_rows=[]

    for target in targets:

        rows = parse_nmap_xml(run_nmap_scan(target))

        all_rows.extend(rows)

    df = pd.DataFrame(all_rows)

    vt={}

    for ip in df["ip"].unique():

        vt[ip]=check_virustotal(ip,VT_API_KEY)

        time.sleep(15)

    df["malicious_reports"]=df["ip"].map(vt)

    df["risk_score"]=df.apply(calculate_risk,axis=1)

    df["severity"]=df["risk_score"].apply(classify_severity)

    st.session_state.df=df

# -------------------------------
# SAMPLE DATA IF NONE
# -------------------------------
if "df" not in st.session_state:
    st.session_state.df = None

# -------------------------------
# LOAD DATA SAFELY
# -------------------------------
if st.session_state.df is None:

    df = pd.DataFrame({
        "ip": [
            "192.168.1.1","192.168.1.1","192.168.1.2",
            "192.168.1.2","192.168.1.3","192.168.1.3"
        ],
        "port": ["22","80","21","443","23","8080"],
        "service": ["ssh","http","ftp","https","telnet","http"],
        "malicious_reports": [0,1,2,3,5,4]
    })

    df["risk_score"] = df.apply(calculate_risk, axis=1)
    df["severity"] = df["risk_score"].apply(classify_severity)

else:
    df = st.session_state.df


# -------------------------------
# PAGE: CYBERSCAN
# -------------------------------
if menu=="CyberScan":

    st.subheader("Dashboard Overview")

    c1,c2,c3,c4=st.columns(4)

    c1.metric("Hosts",df["ip"].nunique())
    c2.metric("Open Ports",len(df))
    c3.metric("Services",df["service"].nunique())
    c4.metric("Max Risk",df["risk_score"].max())


# -------------------------------
# PAGE: SCAN DATA
# -------------------------------
elif menu=="Scan Data":

    st.subheader("Scan Results")

    st.dataframe(df,use_container_width=True)


# -------------------------------
# PAGE: CHARTS
# -------------------------------
elif menu=="Charts":

    st.subheader("📊 Security Charts")

    # 1️⃣ Severity Pie
    sev_df = df["severity"].value_counts().reset_index()
    sev_df.columns = ["severity", "count"]

    fig1 = px.pie(sev_df, names="severity", values="count")
    st.plotly_chart(fig1, use_container_width=True)

    # 2️⃣ Risk per Host
    risk_df = df.groupby("ip")["risk_score"].sum().reset_index()

    fig2 = px.bar(risk_df, x="ip", y="risk_score")
    st.plotly_chart(fig2, use_container_width=True)

    # 3️⃣ Services
    svc_df = df["service"].value_counts().reset_index()
    svc_df.columns = ["service", "count"]

    fig3 = px.bar(svc_df, x="service", y="count")
    st.plotly_chart(fig3, use_container_width=True)

    # 4️⃣ Severity by Host (THIS FIXES YOUR ERROR)
    chart_df = df.groupby(["ip","severity"]).size().reset_index(name="count")

    fig4 = px.bar(
        chart_df,
        x="ip",
        y="count",
        color="severity"
    )

    st.plotly_chart(fig4, use_container_width=True)


# -------------------------------
# PAGE: THREAT INTEL
# -------------------------------
elif menu=="Threat Intel":

    st.subheader("Threat Intelligence")

    high=df[df["severity"]=="High"]

    if high.empty:
        st.success("No High Risk Hosts")
    else:
        st.error(f"{len(high)} High Risk Entries Detected")

        st.dataframe(high)


# -------------------------------
# PAGE: ALERTS
# -------------------------------
elif menu=="Alerts":

    st.subheader("Email Alert System")

    st.write("Send alert email when high risk vulnerabilities detected.")

'''

with open('dashboard.py', 'w', encoding='utf-8') as f:
    f.write(dashboard_code)

lines = len(open('dashboard.py', encoding='utf-8').readlines())
size  = os.path.getsize('dashboard.py')
print(f'dashboard.py  ✅  {lines} lines  |  {size:,} bytes')

os.makedirs('.streamlit', exist_ok=True)
config = '''
[theme]
primaryColor             = "#4f8ef7"
backgroundColor          = "#0f1117"
secondaryBackgroundColor = "#1a1d2e"
textColor                = "#e2e8f0"
font                     = "sans serif"
'''
open('.streamlit/config.toml', 'w').write(config)
print('.streamlit/config.toml  ✅')
print()
print('Now run the two launch cells below ↓')

import os
lines = len(open('dashboard.py', encoding='utf-8').readlines())
size  = os.path.getsize('dashboard.py')
print(f'dashboard.py  ✅  {lines} lines  |  {size:,} bytes')

os.makedirs('.streamlit', exist_ok=True)
config = '''
[theme]
primaryColor             = "#4f8ef7"
backgroundColor          = "#0f1117"
secondaryBackgroundColor = "#1a1d2e"
textColor                = "#e2e8f0"
font                     = "sans serif"
'''
open('.streamlit/config.toml', 'w').write(config)
print('.streamlit/config.toml  ✅')
print()
print('Now run the two launch cells below ↓')

import subprocess, threading, time

def run_streamlit():
    subprocess.run(['streamlit', 'run', 'dashboard.py',
                    '--server.port', '8501', '--server.headless', 'true'])

threading.Thread(target=run_streamlit, daemon=True).start()
time.sleep(5)
print('Streamlit running on port 8501')
print('Now run Cell B below to open the Cloudflare tunnel.')

#!pkill streamlit
#!pkill cloudflared

#import subprocess, threading, time

#def run_streamlit():
 #   subprocess.run(['streamlit', 'run', 'dashboard.py',
  #                  '--server.port', '8501',
   #                 '--server.headless', 'true'])

#threading.Thread(target=run_streamlit, daemon=True).start()
#time.sleep(5)

#print("✅ Streamlit running")

!cloudflared tunnel --url http://localhost:8501

