# -*- coding: utf-8 -*-
"""info_assign2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-z3Oz7xxEwXOTRr-hxqgA0a3i0qlkv1L
"""

!pip install python-nmap requests lxml

import nmap

import xml.etree.ElementTree as ET
import pandas as pd

# Load XML file
tree = ET.parse('/content/drive/MyDrive/scanme_results.xml')
root = tree.getroot()

data = []


for host in root.findall('host'):
    address = host.find('address').get('addr')

    for port in host.findall(".//port"):
        port_id = port.get('portid')
        protocol = port.get('protocol')
        state = port.find('state').get('state')

        service = port.find('service')
        if service is not None:
            service_name = service.get('name')
            product = service.get('product')
            version = service.get('version')
        else:
            service_name = product = version = None

        data.append({
            "IP Address": address,
            "Port": port_id,
            "Protocol": protocol,
            "State": state,
            "Service": service_name,
            "Product": product,
            "Version": version
        })
print(data)
df = pd.DataFrame(data) #converted to dataframe to understand the data better visually
df

open_ports = df[df["State"] == "open"]
open_ports

for host in root.findall('host'):
    for script in host.findall(".//script"):
        print("Script ID:", script.get('id'))
        print("Output:", script.get('output'))
        print("-"*50)

import requests
from google.colab import userdata

API_KEY = userdata.get('API_KEY')

BASE_URL = "https://www.virustotal.com/api/v3/ip_addresses/45.33.32.156"

headers = {
    "x-apikey": API_KEY
}

response = requests.get(BASE_URL, headers=headers)

if response.status_code == 200:
    data = response.json()

    attributes = data['data']['attributes']

    print("IP Address:", data['data']['id'])
    print("Reputation Score:", attributes.get('reputation'))
    print("Country:", attributes.get('country'))
    print("ASN:", attributes.get('asn'))
    print("Network:", attributes.get('network'))
    print("Last Analysis Stats:")
    print(attributes.get('last_analysis_stats'))

else:
    print("Error:", response.status_code)
    print(response.text)

